# -*- coding: utf-8 -*-
"""수학서연0307.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AjIS6M53vYPVTGDQQTuo8SB34zfiUx0D

# 파이썬 기본 자료형
* 자료형: 정수형(int), 실수형(float), 복소수형
* bool형: True, Flase
"""

print('Hello World!')

print(100 + 200)

print('100' + '200')

print('개' + '냥이')