# -*- coding: utf-8 -*-
"""수학서연_과제1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nvzlEHRuivq_HBBvxLXypHAfPgP3nMce
"""

#연습문제 104p. 8번
color = ['빨강','주황','노랑']
name = ['존','메리']
#print(id(new))
print(id(color))

new = color
print(id(new))
print(id(color))

color = ['빨강','주황','노랑']
name = ['존','메리']
new = color
new.append(name[0])
print(color)
print(new)
new = color[1]
print(id(new))
print(id(color))
print(color)
print(new)

"""#조건문"""

if 조건식:
    실행문장
    실행문장

if 조건식:
    실행문장1
    실행문장2
else: #else 뒤에는 조건문을 적지 않는다.
    실행문장3
    실행문장4

if 조건식:
    실행문장1
    실행문장2
elif 조건식: #elif는 여러개 나올수 있음.
    실행문장3
    실행문장4
else:
    실행문장5

if 1:
    print('good')
else:
    print('False')

if 0:
    print('good')
else:
    print('False')

print(3>5)

print(3>5 <10) # 3>5 and 5<10 , False and True

print((3>5) <10) # 0<10

score = int(input ("Enter your scoge: "))

if score >= 90:
    grade = 'A'
if score >= 80:
    grade = 'B'
if score >= 70:
    grade = 'C'
if score >= 60:
    grade = 'D'
if score < 60:
    grade = 'F'
print (grade) # 올바른 값은 A출력이 나와야함.

score = int(input ("Enter your scoge: "))

if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
elif score >= 60:
    grade = 'D'
else:
    grade = 'F'
print (f'{grade} 학점 입니다.')

year = int(input ("출생년도 입력: "))
age = 2024 - int(year) + 1

if age <= 26 and age >= 20:
    print("대학생")
elif age < 20 and age >= 17:
    print("고등학생")
elif age < 17 and age >= 14:
    print("중학생")
elif age <= 14 and age >= 8:
    print("초등학생")
else:
    print ("학생이 아닙니다.")

"""# 반복문
* for문: 주어진 횟수만큼 반복분을 실행
* while문: 주어진 조건식이 참인 동안 반복문 실행
"""

#for문 형식, 범위(리스트, range, 문자열)
for i in [-,1,2]:
    print('hello')

for i in [0,1,2]:
    print('hello')

for i in [0,1,2]:
    print(i, 'hello')

num = [0,1,2]
for i in num:
    print(i, 'hello')

""",(콤마)
''(작은따옴표), ""(큰따옴표)
"""

for i in range(1,4): # 1이상 4미만의 수들만큼 반복
    print(f'{i}번 학생 hello')

for i in range(1,11): # 1이상 11미만의 수들만큼 반복
    print(f'{i}번 학생 hello')

# 홀수 번만
for i in range(1,11,2): # 1이상 11미만의 수들만큼 반복
    print(f'{i}번 학생 hello')

# 짝수 번만
for i in range(2,11,2): # 1이상 11미만의 수들만큼 반복
    print(f'{i}번 학생 hello')

for i in range(1,5): # 1이상 11미만의 수들만큼 반복
    print(f'{2*i + 1}번 학생 hello')

for i in range(10,0,-1): # -1을 붙여 역순환
    print(f'{i}')
else:
    print('fire!')

for j in 'python':
    print(f'{j}번 학생 Hello')

text = 'python'
for j in text:
    print(f'{j}번 학생 Hello')

for j in 'I love you!':
    print(f'{j}행 *')

for i in range(0,3):
    print(i,'*')

for i in range(0,3): # i->    0,     1,     2
    for j in range(3):# j-> 0,1,2 / 0,1,2 / 0,1,2
        print(i, j, '*')#  *,*,* / *,*,* / *,*,*
    print()

for i in range(0,3): # i->    0,     1,     2
    for j in range(3):# j-> 0,1,2 / 0,1,2 / 0,1,2
        print('*', end = '')#  *,*,* / *,*,* / *,*,*
    print()

for i in range(2,10): # i->    2,     3,     4
    for j in range(1,10):# j-> 1,2,3,...,9 /1,2,3,...,9 /1,2,3,...,9
        print(f'{i} * {j} = {i*j}')#  @
    print()

# break문
for i in range(10):
    if i ==5:

# continue문
for i in range(10):
    if i ==5:
        continue
    print(i)

"""#연습문제 156p. 서연 답안(7,9번 제외)
* 1번: 2
* 2번: 3
* 3번: 4
* 4번: 3
* 5번: 4, 5
* 6번: 5
* 7번: 1
* 8번: 4
* 9번: 5
* 10번: 2
* 11번: 4
* 12번: 2
* 13번: 2
* 14번: 1
"""

# 1번 문제
year = int(input('나이를 입력하세요.: '))

if 1 <= year <= 7:
    print('아직 학교를 다닐 나이가 아닙니다. ')
elif 8 <= year <= 13:
    print('초등학생입니다. ')
elif 14 <= year <= 16:
    print('중학생입니다. ')
elif 17 <= year <= 19:
    print('고등학생입니다. ')
elif 20 <= year:
    print('성인입니다. ')
else:
    print('1부터의 정수를 입력해 주세요.')

# 2번 문제
for a in range(8):
    a *= (a-1)
print(a)

# 4번 문제
t = '5'

for n in range(int(t)):
    print('t')

# 6번 문제
my_list = ['i', 'like', 'studying', 'python ']
new_list = []
i = len(my_list)
if i == 4:
    new_list.append (my_list[::2])
print(new_list)

# 7번 문제
num =[1,2,3,4,5,6]
total = 1
for n in num:
    total = n * n

# 10번 문제
numbers = ['10', '11', '12', '13', '14', '15', '16', '17']
total = 0
for number in numbers:
    if int(number) %5 == 0:
        total += int(number)
    else:
        total += 10
print(total)

money = 1500
snack = 500
water = 1000
while money != 0:
    if money > 1000:
        money -= water
    elif 0 <money <= 1000:
        money -= snack * 2
    else:
        money = money + 500
print(money)

# 13번 문제
list_data_a =[1, 2]
list_data_b =[3, 4]
for i in list_data_a:
    for j in list_data_b:
        result = i + j
print(result)

list_1 = [[1,2], [3], [4,5,6]]
a,b,c = list_1
list_2 = a + b + c
print(list_2)