# -*- coding: utf-8 -*-
"""수학서연0321

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xsT0vJW-5SNRdXQKTUXrmdAFIyiP_njZ

# 리스트
* 인덱싱
* 슬라이싱
* 연결연산자, 반복연산자, 포함연산자
* 추가, 삭제
"""

numList = [10,20,30,40,50]
print(numList[0])
print(numList[-1])
print(len(numList))
print(numList[len(numList)-1])

numList = [10,20,30,40,50]
print(numList[:])
print(numList[1:])
print(numList[1:4]) #1이상 4미만의 요소들만 추출
print(numList[1:4:2])
print(numList[::-1])

numList = [10,20,30,40,50]
nameList = ['kim', 'park']
print(nameList + numList)
print(len(nameList) + len(numList))

numList = [10,20,30,40,50]
nameList = ['kim', 'park']
totalList = numList + nameList
print(totalList)
print(totalList[5])
print(totalList[4:6])
print(totalList[-1])
print(totalList[::-1])
print(totalList[::-3])

nameList = ['kim', 'park']
print(nameList*3)

# 포함연산자(in, not in)
nameList = ['kim', 'park']
print('kim' in nameList)
print('kim' not in nameList)
print('lee' in nameList)
print('lee' not in nameList)

nameList = ['kim', 'park']
nameList.append('kang')
print(nameList)

# None
nameList = ['kim', 'park']
print(nameList.append('kang'))

numList = [100,20,350,40,150]
numList.sort()
print(numList)

# None
numList = [100,20,350,40,150]
print(numList.sort())

print(len(nameList))

nameList = ['kim', 'park', 'kang']
nameList.insert(1,'lee')
print(nameList)

nameList = ['lee', 'kim', 'park', 'kang']
numList = [10,20,30]
nameList.extend(numList)
print(nameList)

nameList = ['lee', 'kim', 'park', 'kang']
numList = [10,20,30]
numList.extend(nameList)
print(numList)

numList = [10, 20, 30, 'lee', 'kim', 'park', 'kang']
numList.remove('lee')
print(numList)

numList = [10, 20, 30, 'kim', 'park', 'kang']
numList[3] = 'cha'
print(numList)

numList = [10, 20, 30, 'cha', 'park', 'kang']
del numList[3]
print(numList)

print(numList)
del numList

# NameError: name 'numList' is not defined
del numList
print(numList)

nameList = ['kim', 'park'] #패킹
name1, name2 = nameList #언패킹
print(name1, name2)

# ValueError: not enough values to unpack (expected 3, got 2)
nameList = ['kim', 'park'] #패킹
name1, name2, name3 = nameList #언패킹
print(name1, name2, name3)

nameList = ['kim', 'park', 'lee']
print(id(nameList))

print(id(nameList[0]))
print(id(nameList[1]))
print(id(nameList[2]))

a = 300
b = 300
print(a is b) #a와 b의 주소 위치 다르므로 false
print(id(a))
print(id(b))
print(a == b) # a와 b의 값은 같다 True

kor_score = [49, 79, 20, 100, 80]
math_score = [43, 59, 85, 30, 90]
eng_score = [49, 79,48, 60, 100]

midterm_score = [kor_score, math_score, eng_score]
print(midterm_score)

math_score[0] = 1000
print(midterm_score)

a = ["color", 1, 0.2]
color = ['노랑', '파랑', '초록', '검정', '보라']
a[0] = color # 리스트 안에 리스트도 입력 가능
print(a)

# 3장 연습문제 1번
a = [1]
b = ['a', 'b', 'c']
b[1] = a[0]
print(b)