# -*- coding: utf-8 -*-
"""수학서연0314

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d6waSg3X4AW8sf4-qBa-Gdd0piqOmbWR

# 파이썬 기본 자료형(Data Type)
* 숫자형: 정수형(int), 실수형(float)
* 불(bool)형: True, False
"""

카페 = 30000
네페 = 20000
print(카페 + 네페)

카페 = 15000
네페 = 20000
print(카페 + 네페)

네페 = 카페
print(네페)

카페 = 네페
print(카페)

# NameError: name 'num_2' is not defined
num1 = 15000
num2 = 20000
print(num1 + num_2)

# SyntaxError: invalid decimal literal
1num = 15000
2num = 20000
print(1num + 2num)

"""# 변수명 작성 규칙
* 알파벳, 숫자. _(언더바) 사용
* 알파벳 대소문자 구별
* 숫자는 맨앞에 올 수 없다
* 중간에 공백은 올 수 없다
* 특수기호 사용X, 단, _(언더바) 허용
* 예약어 사용X
* 낙타체,스네이크체 (예)numList,my_car(O),my car(X),1nim(X)
"""

# 출력함수, print()
name, age = 'hong' , 20
print(name, age)

print(id(name))

# ValueError: too many values to unpack (expected 2)
name, age = 'hong' , 20, 'seoul'
print(name, age)

# 자료형 확인함수, type()
num1 = 100
print(num1)
print(type(num1))

num1 = 10.0
print(num1)
print(type(num1))

print(int(num1))

num2 = '20.0'
print(type(num2))

# ValueError: invalid literal for int() with base 10: '20.0'
num2 = '20.0'
print(int(num2))

num2 = '20.0'
print(float(num2))

num3 = float(num2)
print(int(num3))

print(type(True))

print(type('Hello~'))

"""# 산술연산자
* +, -, (곱셈), /, //(몫), %(나머지), **(거듭제곱)
* 총 7가지 종류
"""

a, b, c = 12, 3, 5
a = a+2 #12+2, a+=2 (복합대입연산자)
a -= b #14-3
a %= c #11%5
print(a**3)

#연결연산자, 반복연산자
a = 3.14
b = 314.15
aa = str(a)
bb = str(b)
print(aa + bb) #연결연산자, 문자열+문자열
print('='*30) #반복연산자, 문자열*정수형
print(aa * 10)

print('개' + '냥이')
print('개냥이' * 10)

# TypeError: can't multiply sequence by non-int of type 'str'
print('개' * '냥이')

# TypeError: can only concatenate str (not "int") to str
print('개냥이' + 10)

"""# 관게(비교) 연산자
* >, <, >=, <=, ==, !=
"""

a, b, c = 12, 3, 5
print(a>b) #12>3, True

print(a<b) #12<3, Flase
print(a==b) #12==3, Flase
print(a!=b) #12!=3, True

"""# 논리연산자
* and(직렬), or(병렬), not(역)
"""

a, b, c = 12, 3, 5
print(a>b and a!=b) #12>3 and 12!=3, True and True
print(a>b and a==b and b<c) #12>3 and 12==3 and 3<5, True and Flase and True

a, b, c = 12, 3, 5
print(a>b or a!=b) #12>3 or 12!=3, True
print(a>b or a==b) #12>3 or 12==3, True

a, b, c = 12, 3, 5
print(not(a>b or a!=b))